### PR TITLE
Updated the neos version to mainline, this also includes the JP character fix

### PR DESCRIPTION
**Pull request by Earthmark**
This was created using tyhe msdfgen mainline the authority, then re-applying the neos changes on top of that. This is significantly less of a clustertruck than the PR that applies the msdfgen mainline changes on top of the neos changes: https://github.com/Neos-Metaverse/msdfgen/pull/1

### CODE REVIEW

**Review by SnooperXP — APPROVED** [review]
LGTM, just need to check if we need the solution files and vc projects added to the code base. I'm not sure what is needed in terms of the pipelines.

**Comment by Earthmark** [comment]
They're not used in the pipelines but the base repo has them for a dev environment. It looked like froox customized the project for his changes as well, so this pull requests updates both the cmake and project files, although only the cmake files are used in the build pipeline.

**Comment by Earthmark** [comment]
Thank you for bringing this up, the new changes do  pivot from using msbuild for Windows, CMake for Linux, and a static checked in Android build; to using cmake across the board. However, the cmake build is going to be using msbuild internally for Windows, but it might be a different toolchain. Either some testing to ensure the library works on a clean machine may be needed (in case a new cv++ redistributable is needed), or something to pivot the windows builds back to a known toolchain.

**Comment by Earthmark** [comment]
The vc++ redis is now a fixed value, it should be valid although I have yet to find which version steam distributes.

**Comment by Earthmark** [comment]
Thank you for the feedback, I updated the usage to your first suggestion. It seems to work very well, and resolves some artifacts I had seen before.

**Pull request merged**
